/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;
import java.util.Scanner;
import java.util.ArrayList;

 public class App {
     public static void main(String[] args){
      /* System.out.println("Welcome to the EStoreSearch\n");
       Scanner scannerObj = new Scanner(System.in);*/
       int flag1 = 1; //set flag to 1 for command loop testing
       String filename="none";
        if(args.length == 0){
            filename="none";
       }else{
          filename = args[0];
        }
        EStoreSearch eStore = new EStoreSearch(filename);  //define class
        /*String filename="none";
         if(args.length == 0){
             filename="none";
        }else{
           filename = args[0];
          // EStoreSearch eStore = new EStoreSearch(filename);
            eStore.setFileName(args[0]);
            eStore.readFile(filename);
        }*/
      //  EStoreSearch eStore = new EStoreSearch();
        eStore.setVisible(true);

/*
       while(flag1 == 1){
         System.out.println("Would you like to add, search, or quit? \n");
         String userInput = scannerObj.nextLine();
         //scannerObj.nextLine();
         if(userInput.equalsIgnoreCase("add")||userInput.equalsIgnoreCase("a")){
           int i =0;
           int flag2 =1;
           while(flag2==1){
             i = eStore.getItem();
             if(i==1){
               flag2 =2;
               eStore.setBook();
             }if(i==2){
               flag2 =2;
               eStore.setElectronics();
             }
           }
         }if(userInput.equalsIgnoreCase("search")|| userInput.equalsIgnoreCase("s")){
           eStore.getSearchRequest();
         }if(userInput.equalsIgnoreCase("quit")||userInput.equalsIgnoreCase("q")){
           flag1 =2;
         }else{
           flag1 =1;
         }
       }*/

     }
 }
